### ISSUE TITLE
ComboBoxGadget backgroundcolor of the main box does not change

### ISSUE THREAD

**Issue by lgb-this** [ChrisRfr/ObjectColor-Dark-Mode#1]
I need to color the background of the main box of the ComboBoxGadget . I made a test with this code:

```
ComboBoxGadget(300,10,190,100,20,#CBS_HASSTRINGS|#CBS_OWNERDRAWFIXED)
For a = 1 To 5
  AddGadgetItem(300,-1,"ComboBox item " + Str(a))
Next
SetObjectColor(#PB_All,300,#Cyan,#Blue)
```

The main box stays white and only the dropdown list has a cyan background color.

![p1](https://github.com/ChrisRfr/ObjectColor-Dark-Mode/assets/16973456/ed9b7cb2-b831-447b-aa60-17fcacfa19ed)
![p2](https://github.com/ChrisRfr/ObjectColor-Dark-Mode/assets/16973456/2a137b70-a8c3-4214-bed9-8f7f1cd520c7)

**Comment by ChrisRfr** [comment]
Yes, this is the case when no element is selected (no SetGadgetState(#Combo, 0))
I've updated to version 1.5.1, to also paint the background color in this case.

**Comment by lgb-this** [comment]
Thanks for the fix. The coloring works now for the ComboBoxGadget.

**Comment by lgb-this** [comment]
I made some additional tests with the ComboBoxGadget:

```
ComboBoxGadget(300,10,190,100,20,#CBS_HASSTRINGS|#CBS_OWNERDRAWFIXED)
For a = 1 To 15
  AddGadgetItem(300,-1,"ComboBox item " + Str(a))
Next
SetGadgetState(300,4)
SetObjectColor(#PB_All,300,#Cyan,#Blue)
SetObjectColor(#PB_All,300, #PB_Auto,#PB_Auto)

ComboBoxGadget(303,10,220,100,20)
For a = 1 To 15
  AddGadgetItem(303,-1,"ComboBox item " + Str(a))
Next
SetGadgetState(303,4)
```

The second ComboBoxGadget shows a white background as it is normal. The first ComboBoxGadget does not return to white, but shows some gray.

![p4](https://github.com/ChrisRfr/ObjectColor-Dark-Mode/assets/16973456/77c4aab5-bea7-4cef-8a34-a9b27ed6fc54)

**Comment by ChrisRfr** [comment]
This is the normal behavior, in ObjectColor, with #PB_Auto the color is the Parent Gadget one, not the default value.
And If the Parent BackColor = #PB_Default, I use GetSysColor_(#COLOR_3DFACE) by default.
For a white ComboBoxbackground, use: SetObjectColor(#PB_All,300, #White,#PB_Auto)

ObjectColor is designed to color gadgets from the window to its children, usually with a background color for the window. 
I haven't tested it further with the window's default color.

Otherwise, you should consider using [ObjectTheme](https://github.com/ChrisRfr/ObjectTheme), rather than ObjectColor, as it's more complete, customizable and powerful, without calculations when drawing.

**Comment by lgb-this** [comment]
Thanks for the hints. I want to show the user changes in some gadgets and the idea is to change the background color of these changed gadgets.

The ComboBoxGadget is very difficult to handle. If the gadget is active, the colors are not readable. The selection is blue with black text.

![p5](https://github.com/ChrisRfr/ObjectColor-Dark-Mode/assets/16973456/7aa7fd40-9b37-47d8-9f04-ae11f65e6ff3)

```
ComboBoxGadget(303,10,220,100,20,#CBS_HASSTRINGS|#CBS_OWNERDRAWFIXED)
For a = 1 To 15
  AddGadgetItem(303,-1,"ComboBox item " + Str(a))
Next
SetGadgetState(303,4)
SetObjectColor(#PB_All,303,#Cyan,#Blue)
```

**Comment by ChrisRfr** [comment]
ObjectTheme use the windows default color for Highlight : GetSysColor_(#COLOR_HIGHLIGHT) 
It is hard coded but you can change it on line 1135, if needed.

That's another reason why ObjectTheme is better, you can define each colors or leave the default values, example for ComboBox:

```
Data.l #PB_GadgetType_ComboBox,  #PB_Gadget_BackColor,       #PB_Default
Data.l #PB_GadgetType_ComboBox,  #PB_Gadget_FrontColor,      #PB_Default
Data.l #PB_GadgetType_ComboBox,  #PB_Gadget_GrayTextColor,   #PB_Default
Data.l #PB_GadgetType_ComboBox,  #PB_Gadget_HighLightColor,  #PB_Default
Data.l #PB_GadgetType_ComboBox,  #PB_Gadget_EditBoxColor,    $382521 
```

**Comment by lgb-this** [comment]
Thanks. I made some tests with ObjectTheme, but it is not working as i need it. I have to check another way for my task.
