### ISSUE TITLE
ToolTip only black rectangle

### ISSUE THREAD

**Issue by lgb-this** [ChrisRfr/ObjectColor-Dark-Mode#2]
I made a test with this code:

```
SpinGadget(201,10,40,100,20,1,10)
SetObjectColor(#PB_All,201,#Cyan,#Blue)
GadgetToolTip(201,"Test XYZ")
```

I get this result:

![p3](https://github.com/ChrisRfr/ObjectColor-Dark-Mode/assets/16973456/7e0d10f9-41d5-4b80-b4b5-28fdcd8bb7dd)

What do i have to change to see the ToolTip again ?

**Comment by ChrisRfr** [comment]
I've fixed it, I keep the default theme for tooltips now, if the window uses the default color, without SetWindowColor()

**Comment by lgb-this** [comment]
Thanks. It works now.
